version: '3.8'

services:
  # MediaMTX RTSP Server
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"  # RTSP port
      - "8888:8888"  # HTTP API port
      - "8889:8889"  # Metrics port
    networks:
      - video-network
    restart: unless-stopped

  # Video Gateway Application
  video-gateway:
    build: .
    container_name: video-gateway
    ports:
      - "8080:8080"
    volumes:
      - c:/tmp:/tmp
      - c:/tmp/hls:/tmp/hls
      - c:/tmp/videos:/tmp/videos
    networks:
      - video-network
    restart: unless-stopped
    environment:
      - MEDIAMTX_HOST=mediamtx
      - MEDIAMTX_PORT=8554
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '0.5'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 32768
        hard: 32768
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

networks:
  video-network:
    driver: bridge
    name: video-gateway-network
